Repository prgrms-be-devcourse/NBE1_2_Team06, pull requests merged in 2024-10, with the labels that each got.

#49 [#36] [FEATURE] 응급실 지도 API 구현
  ea-application/app-api/src/main/java/com/nbe2/api/emergencyroom/EmergencyRoomApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/emergencyroom/dto/EmergencyRoomMapResponse.java
  ea-domain/build.gradle
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoom.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomInfo.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomMapInfo.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomReader.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomRepository.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomRepositoryCustom.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomRepositoryImpl.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomService.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/exception/EmergencyRoomErrorCode.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/exception/InvalidCoordinateException.java
  ea-domain/src/main/resources/application-domain.yml
  ea-infra/build.gradle
  ea-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 지원

#48 [#27] [REFACTOR] DB 중복 저장 방지
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoom.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomInitializer.java
Labels: ♻️ refactor, 종원

#42 [#38] [FEATURE] 챗봇 구현
  build.gradle
  ea-application/app-api/build.gradle
  ea-application/app-api/src/main/java/com/nbe2/api/chatbot/ChatbotApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/chatbot/dto/QuestionRequest.java
  ea-application/app-api/src/main/java/com/nbe2/api/chatbot/dto/SessionResponse.java
  ea-domain/src/main/java/com/nbe2/domain/chatbot/ChatbotService.java
  ea-domain/src/main/java/com/nbe2/domain/chatbot/Question.java
  ea-infra/build.gradle
  ea-infra/src/main/java/com/nbe2/infra/chatbot/client/OpenAiClient.java
  ea-infra/src/main/java/com/nbe2/infra/chatbot/config/ChatClientConfig.java
  ea-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 수빈

#44 [#35] [REFACTOR] 회원가입, 로그인 관련 임시 구현 리팩토링
  ea-application/app-api/src/main/java/com/nbe2/api/auth/AdminAuthApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/auth/AuthApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/auth/test.java
  ea-application/app-api/src/main/java/com/nbe2/api/global/config/CustomSecurityFilter.java
  ea-application/app-api/src/main/java/com/nbe2/api/global/config/SecurityConfig.java
  ea-application/app-api/src/main/java/com/nbe2/api/global/crypto/BcryptPasswordEncoder.java
  ea-application/app-api/src/main/java/com/nbe2/api/user/UserApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/user/dto/MedicalRequest.java
  ea-domain/src/main/java/com/nbe2/domain/auth/AuthService.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomReader.java
  ea-domain/src/main/java/com/nbe2/domain/user/ApprovalStatus.java
  ea-domain/src/main/java/com/nbe2/domain/user/MedicalPersonInfo.java
  ea-domain/src/main/java/com/nbe2/domain/user/MedicalProfile.java
  ea-domain/src/main/java/com/nbe2/domain/user/TempFile.java
  ea-domain/src/main/java/com/nbe2/domain/user/User.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserAppender.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserReader.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserRepositoryCustom.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserRepositoryImpl.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserService.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserUpdater.java
  ea-domain/src/test/java/com/nbe2/domain/auth/AuthServiceTest.java
  ea-domain/src/test/java/com/nbe2/domain/user/UserAppenderTest.java
  ea-domain/src/test/java/com/nbe2/domain/user/UserFixture.java
  ea-domain/src/test/java/com/nbe2/domain/user/UserReaderTest.java
  ea-infra/src/main/java/com/nbe2/infra/auth/SecurityPasswordEncoder.java
Labels: ♻️ refactor, 수빈

#47 [#41] [FEATURE] 게시글의 댓글 기능 구현
  ea-application/app-api/src/main/java/com/nbe2/api/post/CommentApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/PostApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/CommentRegisterRequest.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/CommentResponse.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/CommentUpdateRequest.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/PostResponse.java
  ea-domain/src/main/java/com/nbe2/domain/posts/entity/Comment.java
  ea-domain/src/main/java/com/nbe2/domain/posts/entity/Post.java
  ea-domain/src/main/java/com/nbe2/domain/posts/exception/CommentErrorCode.java
  ea-domain/src/main/java/com/nbe2/domain/posts/exception/CommentNotFoundException.java
  ea-domain/src/main/java/com/nbe2/domain/posts/exception/CommentWriterMismatchException.java
  ea-domain/src/main/java/com/nbe2/domain/posts/repository/CommentRepository.java
  ea-domain/src/main/java/com/nbe2/domain/posts/repository/PostRepository.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/CommentService.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/PostService.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/component/CommentAppender.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/component/CommentDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/component/CommentReader.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/component/CommentUpdater.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/component/CommentValidator.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/component/PostDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/component/PostReader.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/dto/CommentInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/dto/CommentReadInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/dto/CommentWriteInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/dto/PostDetailsInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/dto/PostListInfo.java
  ea-domain/src/main/resources/application-domain.yml
Labels: ✨ feature, 형석

#58 [#54] [FEATURE] 좋아요 기능 구현
  ea-application/app-api/src/main/java/com/nbe2/api/post/CommentApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/LikeApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/PostApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/CommentResponse.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/LikeRequest.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/PostRegisterRequest.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/PostResponse.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/dto/PostUpdateRequest.java
  ea-domain/src/main/java/com/nbe2/domain/posts/City.java
  ea-domain/src/main/java/com/nbe2/domain/posts/Comment.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentAppender.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentReadInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentReader.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentRepository.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentService.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentUpdater.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentValidator.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentWriteInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/Like.java
  ea-domain/src/main/java/com/nbe2/domain/posts/LikeAppender.java
  ea-domain/src/main/java/com/nbe2/domain/posts/LikeDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/posts/LikeInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/LikeRepository.java
  ea-domain/src/main/java/com/nbe2/domain/posts/LikeService.java
  ea-domain/src/main/java/com/nbe2/domain/posts/LikeValidator.java
  ea-domain/src/main/java/com/nbe2/domain/posts/LocalPostPageRequestInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/Post.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostAppender.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostDefaultInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostDetailsInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostListInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostReader.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostRepository.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostService.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostUpdater.java
  ea-domain/src/main/java/com/nbe2/domain/posts/UserPostPageRequestInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/service/dto/PostListInfo.java
  ea-domain/src/test/java/com/nbe2/domain/post/PostAppenderTest.java
Labels: ✨ feature, 형석

#61 [#60] [FEATURE] 게시글 파일 추가 기능 구현
  ea-application/app-api/src/main/java/com/nbe2/api/post/CommentApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/post/PostApi.java
  ea-domain/src/main/java/com/nbe2/domain/posts/Post.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostAppender.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostDefaultInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostDetailsInfo.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostFile.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostFilePk.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostFileSetter.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostService.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostUpdater.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostWriteInfo.java
Labels: ✨ feature, 형석

#59 [#50] [FEATURE] 사용자 프로필 조회,수정 추가
  ea-application/app-api/src/main/java/com/nbe2/api/post/PostApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/user/UserApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/user/dto/ProfileResponse.java
  ea-application/app-api/src/main/java/com/nbe2/api/user/dto/UpdatePasswordRequest.java
  ea-application/app-api/src/main/java/com/nbe2/api/user/dto/UpdateProfileRequest.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostService.java
  ea-domain/src/main/java/com/nbe2/domain/user/MyProfile.java
  ea-domain/src/main/java/com/nbe2/domain/user/UpdatePassword.java
  ea-domain/src/main/java/com/nbe2/domain/user/UpdateProfile.java
  ea-domain/src/main/java/com/nbe2/domain/user/User.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserProfile.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserService.java
  ea-domain/src/main/java/com/nbe2/domain/user/UserUpdater.java
  ea-domain/src/main/java/com/nbe2/domain/user/exception/InvalidPasswordException.java
  ea-domain/src/main/java/com/nbe2/domain/user/exception/UserErrorCode.java
  ea-domain/src/test/java/com/nbe2/domain/user/UserServiceTest.java
  ea-domain/src/test/java/com/nbe2/domain/user/UserUpdaterTest.java
  ea-security/src/main/java/com/nbe2/security/utils/JwtGenerator.java
Labels: ✨ feature, 수빈

#78 [#77] [HOTFIX] 사용자 권한 오류 수정
  ea-domain/src/main/java/com/nbe2/domain/user/UserRole.java
  ea-security/src/main/java/com/nbe2/security/config/CustomSecurityFilter.java
  ea-security/src/main/java/com/nbe2/security/config/SecurityConfig.java
  ea-security/src/main/java/com/nbe2/security/utils/JwtProvider.java
Labels: 수빈, 🚑 hotfix

#73 [#62] [FEATURE] 알림 시스템 구현
  ea-application/app-api/src/main/java/com/nbe2/api/global/config/CursorArgumentResolver.java
  ea-application/app-api/src/main/java/com/nbe2/api/global/config/WebConfig.java
  ea-application/app-api/src/main/java/com/nbe2/api/notification/NotificationApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/notification/dto/NotificationDetailResponse.java
  ea-application/app-api/src/main/java/com/nbe2/api/notification/dto/UnreadResponse.java
  ea-application/app-api/src/main/java/com/nbe2/api/notification/sse/SseConnector.java
  ea-application/app-api/src/main/java/com/nbe2/api/notification/sse/SseEmitterRepository.java
  ea-application/app-api/src/main/java/com/nbe2/api/notification/sse/SseSender.java
  ea-application/app-api/src/main/java/com/nbe2/api/notification/sse/exception/SseConnectionException.java
  ea-application/app-api/src/main/java/com/nbe2/api/notification/sse/exception/SseErrorCode.java
  ea-common/src/main/java/com/nbe2/common/annotation/CursorDefault.java
  ea-common/src/main/java/com/nbe2/common/dto/Cursor.java
  ea-common/src/main/java/com/nbe2/common/dto/CursorResult.java
  ea-domain/src/main/java/com/nbe2/domain/global/config/AsyncConfig.java
  ea-domain/src/main/java/com/nbe2/domain/notification/EventSender.java
  ea-domain/src/main/java/com/nbe2/domain/notification/MessagePublisher.java
  ea-domain/src/main/java/com/nbe2/domain/notification/Notification.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationAppender.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationDetail.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationEvent.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationManager.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationMessage.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationReader.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationRepository.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationRepositoryCustom.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationRepositoryImpl.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationService.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationType.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationUpdater.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentAppender.java
  ea-domain/src/test/java/com/nbe2/domain/notification/NotificationAppenderTest.java
  ea-domain/src/test/java/com/nbe2/domain/notification/NotificationFixture.java
  ea-domain/src/test/java/com/nbe2/domain/notification/NotificationManagerTest.java
  ea-domain/src/test/java/com/nbe2/domain/notification/NotificationReaderTest.java
  ea-domain/src/test/java/com/nbe2/domain/notification/NotificationServiceTest.java
  ea-infra/src/main/java/com/nbe2/infra/naver/config/NaverRequestInterceptor.java
  ea-infra/src/main/java/com/nbe2/infra/notification/client/CommentRedisSubscriber.java
  ea-infra/src/main/java/com/nbe2/infra/notification/client/RedisPublisher.java
  ea-infra/src/main/java/com/nbe2/infra/notification/config/RedisPubsubConfig.java
  ea-infra/src/main/resources/application-infra.yml
  ea-security/src/main/java/com/nbe2/security/utils/JwtGenerator.java
  ea-security/src/main/java/com/nbe2/security/utils/JwtProvider.java
  ea-security/src/main/resources/application-security.yaml
Labels: ✨ feature, 수빈

#70 [#66][FEATURE] 즐겨찾기 기능 구현
  ea-application/app-api/src/main/java/com/nbe2/api/bookmark/BookmarkApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/bookmark/dto/BookmarkReadResponse.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/Bookmark.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/BookmarkAppender.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/BookmarkDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/BookmarkReadInfo.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/BookmarkReader.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/BookmarkRepository.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/BookmarkService.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/exception/BookmarkDuplicatedException.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/exception/BookmarkErrorCode.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/exception/BookmarkNotFoundEmergencyRoomIdException.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeAppender.java
  ea-security/src/main/java/com/nbe2/security/utils/JwtGenerator.java
Labels: ✨ feature, 길현

#71 [#68] [REFACTOR] 게시글 성능 개선
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentReader.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentRepository.java
  ea-domain/src/main/java/com/nbe2/domain/posts/Post.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostAppender.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostFile.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostFileRegisterer.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostFileRepository.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostFileSetter.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostReader.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostRepository.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostService.java
  ea-domain/src/main/java/com/nbe2/domain/posts/PostUpdater.java
  ea-domain/src/main/resources/application-domain.yml
Labels: ♻️ refactor, 형석

#63 [#55][FEATURE] 응급실 리뷰 구현
  build.gradle
  ea-application/app-api/src/main/java/com/nbe2/api/review/ReviewApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/review/dto/ReviewCreateRequest.java
  ea-application/app-api/src/main/java/com/nbe2/api/review/dto/ReviewReadResponse.java
  ea-application/app-api/src/main/java/com/nbe2/api/review/dto/ReviewUpdateRequest.java
  ea-domain/src/main/java/com/nbe2/domain/review/Review.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewAppender.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewInfo.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewReadInfo.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewReader.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewRepository.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewService.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewUpdateInfo.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewUpdater.java
  ea-domain/src/main/java/com/nbe2/domain/review/ReviewValidator.java
  ea-domain/src/main/java/com/nbe2/domain/review/exception/ReviewErrorCode.java
  ea-domain/src/main/java/com/nbe2/domain/review/exception/ReviewNoAccessAuthority.java
  ea-domain/src/main/java/com/nbe2/domain/review/exception/ReviewNotFoundException.java
  ea-infra/src/main/resources/application-infra.yml
  ea-security/src/main/java/com/nbe2/security/utils/JwtGenerator.java
Labels: ✨ feature, 길현

#65 [#64][FEATURE] 응급실 상세 정보 조희 기능 구현
  ea-application/app-api/src/main/java/com/nbe2/api/emergencyroom/EmergencyRoomApi.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/DistanceCalculator.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoom.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomDetailInfo.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomRepositoryCustom.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/EmergencyRoomService.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/RealTimeEmergencyRoomInfoCacheManager.java
  ea-domain/src/main/java/com/nbe2/domain/emergencyroom/RealTimeEmergencyRoomInfoFetcher.java
Labels: ✨ feature, 형석, 길현

#85 [#84] [FEATURE] 프론트 Boilerplate 추가
  ea-security/src/main/java/com/nbe2/security/config/SecurityConfig.java
  ea-security/src/main/java/com/nbe2/security/constants/SecurityUrlEndPoint.java
  ea-vue/.browserslistrc
  ea-vue/.editorconfig
  ea-vue/.eslintrc.js
  ea-vue/.gitignore
  ea-vue/README.md
  ea-vue/babel.config.js
  ea-vue/jsconfig.json
  ea-vue/package-lock.json
  ea-vue/package.json
  ea-vue/public/favicon.ico
  ea-vue/public/index.html
  ea-vue/src/App.vue
  ea-vue/src/assets/logo.png
  ea-vue/src/components/HealthCheck.vue
  ea-vue/src/composables/api.js
  ea-vue/src/main.js
  ea-vue/src/router/index.js
  ea-vue/src/views/AboutView.vue
  ea-vue/src/views/HomeView.vue
  ea-vue/vue.config.js
Labels: ✨ feature, 수빈

#83 [Refactor] 응급실 공지사항 유저 권한 추가
  ea-application/app-api/src/main/java/com/nbe2/api/notice/NoticeApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/notice/dto/NoticeUpdateReqeust.java
  ea-application/app-api/src/main/java/com/nbe2/api/notice/dto/NoticteCreateRequest.java
  ea-domain/src/main/java/com/nbe2/domain/notice/Notice.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeAppender.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeInfo.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeInfoValidator.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeService.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeUpdateInfo.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeUpdater.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeValidator.java
  ea-domain/src/main/java/com/nbe2/domain/notice/exception/NoticeErrorCode.java
  ea-domain/src/main/java/com/nbe2/domain/notice/exception/NoticeNoAccessCreateException.java
  ea-domain/src/main/java/com/nbe2/domain/notice/exception/NoticeNoAccessYoursException.java
  ea-domain/src/main/java/com/nbe2/domain/notice/exception/NoticeNotFoundContentException.java
  ea-domain/src/main/java/com/nbe2/domain/notice/exception/NoticeNotFoundHpIdException.java
  ea-domain/src/main/java/com/nbe2/domain/notice/exception/NoticeNotFoundTitleExcepion.java
Labels: ♻️ refactor, 길현

#89 [#88] [REFACTOR] 실시간 응급실 정보 테스트 코드 수정
  ea-domain/src/test/java/com/nbe2/domain/emergencyroom/RealTimeEmergencyRoomInfoFetcherTest.java
Labels: ♻️ refactor, 길현, :test_tube: test

#82 [#81] [FEATURE] 공지사항 알림 구현
  ea-application/app-api/src/main/java/com/nbe2/api/notification/sse/SseSender.java
  ea-common/src/main/resources/application-common.yml
  ea-domain/src/main/java/com/nbe2/domain/bookmark/BookmarkReader.java
  ea-domain/src/main/java/com/nbe2/domain/bookmark/BookmarkRepository.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NewNoticeEvent.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NewNoticeOfBookmarkedHospitalEvent.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeEventHandler.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeEventInnerPublisher.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeEventPublisher.java
  ea-domain/src/main/java/com/nbe2/domain/notice/NoticeService.java
  ea-domain/src/main/java/com/nbe2/domain/notification/EventSender.java
  ea-domain/src/main/java/com/nbe2/domain/notification/MessagePublisher.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NewNotification.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NewNotificationEvent.java
  ea-domain/src/main/java/com/nbe2/domain/notification/Notification.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationAppender.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationDeleter.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationEvent.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationManager.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationMessage.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationRepository.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationRepositoryCustom.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationRepositoryImpl.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationSender.java
  ea-domain/src/main/java/com/nbe2/domain/notification/NotificationType.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentAppender.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentEventPublisher.java
  ea-domain/src/main/java/com/nbe2/domain/posts/CommentService.java
  ea-domain/src/main/java/com/nbe2/domain/posts/NewCommentEvent.java
  ea-domain/src/test/java/com/nbe2/domain/emergencyroom/EmergencyRoomFixture.java
  ea-domain/src/test/java/com/nbe2/domain/notice/NoticeEventHandlerTest.java
  ea-domain/src/test/java/com/nbe2/domain/notice/NoticeFixture.java
  ea-domain/src/test/java/com/nbe2/domain/notification/NotificationAppenderTest.java
  ea-domain/src/test/java/com/nbe2/domain/notification/NotificationFixture.java
  ea-domain/src/test/java/com/nbe2/domain/notification/NotificationManagerTest.java
  ea-infra/build.gradle
  ea-infra/src/main/java/com/nbe2/infra/notification/client/RedisPublisher.java
  ea-infra/src/main/java/com/nbe2/infra/notification/config/RedisPubsubConfig.java
  ea-infra/src/main/java/com/nbe2/infra/notification/config/SchedulerConfig.java
  ea-infra/src/main/java/com/nbe2/infra/notification/publisher/NoticeRedisPublisher.java
  ea-infra/src/main/java/com/nbe2/infra/notification/publisher/RedisPublisher.java
  ea-infra/src/main/java/com/nbe2/infra/notification/scheduler/NotificationScheduler.java
  ea-infra/src/main/java/com/nbe2/infra/notification/subscriber/CommentRedisSubscriber.java
  ea-infra/src/main/java/com/nbe2/infra/notification/subscriber/NoticeRedisSubscriber.java
  ea-infra/src/main/resources/application-infra.yml
Labels: ✨ feature, 수빈

#91 [#72] [TEST] 게시글 테스트 작성
  ea-domain/src/test/java/com/nbe2/domain/post/CommentServiceTest.java
  ea-domain/src/test/java/com/nbe2/domain/post/LikeServiceTest.java
  ea-domain/src/test/java/com/nbe2/domain/post/PostAppenderTest.java
  ea-domain/src/test/java/com/nbe2/domain/post/PostFixture.java
  ea-domain/src/test/java/com/nbe2/domain/post/PostReaderTest.java
  ea-domain/src/test/java/com/nbe2/domain/post/PostServiceTest.java
Labels: 형석, :test_tube: test

#94 [#90] [FEATURE] 챗봇 화면 구현
  ea-application/app-api/build.gradle
  ea-application/app-api/src/main/java/com/nbe2/api/chatbot/ChatbotApi.java
  ea-application/app-api/src/main/java/com/nbe2/api/chatbot/dto/ChatResponse.java
  ea-domain/src/main/java/com/nbe2/domain/chatbot/ChatbotService.java
  ea-infra/src/main/java/com/nbe2/infra/chatbot/client/OpenAiClient.java
  ea-infra/src/main/java/com/nbe2/infra/chatbot/config/ChatClientConfig.java
  ea-security/src/main/java/com/nbe2/security/constants/SecurityUrlEndPoint.java
  ea-vue/.eslintrc.js
  ea-vue/public/index.html
  ea-vue/src/components/chatbot/ChatbotWindow.vue
  ea-vue/src/components/chatbot/MessageInput.vue
  ea-vue/src/components/chatbot/MessageList.vue
  ea-vue/src/composables/chatbot-api.js
  ea-vue/src/composables/format-chat-message.js
  ea-vue/src/views/ChatbotView.vue
  ea-vue/src/views/HomeView.vue
Labels: ✨ feature, 수빈, 🎨 frontend

#92 [#87] [TEST] 즐겨찾기 관련 기능 테스트 작성
  ea-domain/src/test/java/com/nbe2/domain/bookmark/BookmarkAppenderTest.java
  ea-domain/src/test/java/com/nbe2/domain/bookmark/BookmarkDeleterTest.java
  ea-domain/src/test/java/com/nbe2/domain/bookmark/BookmarkFixture.java
  ea-domain/src/test/java/com/nbe2/domain/bookmark/BookmarkReaderTest.java
  ea-domain/src/test/java/com/nbe2/domain/bookmark/BookmarkServiceTest.java
Labels: 길현, :test_tube: test

#95 [#93] [TEST] 응급실 리뷰 테스트 작성
  ea-domain/src/test/java/com/nbe2/domain/review/ReviewAppenderTest.java
  ea-domain/src/test/java/com/nbe2/domain/review/ReviewDeleterTest.java
  ea-domain/src/test/java/com/nbe2/domain/review/ReviewFixture.java
  ea-domain/src/test/java/com/nbe2/domain/review/ReviewReaderTest.java
  ea-domain/src/test/java/com/nbe2/domain/review/ReviewServiceTest.java
  ea-domain/src/test/java/com/nbe2/domain/review/ReviewUpdaterTest.java
  ea-domain/src/test/java/com/nbe2/domain/review/ReviewValidatorTest.java
Labels: 길현, :test_tube: test
